experimental_monorepo_root = true

[settings]
auto_install = true
#trace = true

[tools]
# -----------------------------------------------------------------------------
gh = "latest"
act = "latest"
# -----------------------------------------------------------------------------
java = "openjdk-21.0.2"
gradle = "latest"

#"aqua:godotengine/godot" = "4.5"
#"github:BurntSushi/ripgrep" = "latest"
#"github:inkle/ink" = "1.1.1"
#act = "latest"
#gh = "latest"

# -----------------------------------------------------------------------------
#[tasks."setup"]
#description = "Download and install a local version of requirement executables to make the project portable"
#depends = [
##    "setup:aqua"
#]

# -----------------------------------------------------------------------------
#[tasks."website"]
#description = "Access to website service"
#dir = "{{cwd}}/services/website"
#run = "mise r website:{{arg(var=true, default='tasks')}}"

#[tasks."engine:editor"]
#dir = "{{cwd}}/src/main/godot"
#run = '{{vars.godot_exec}} -e'
#description = "Open Godot Editor and load the project"

#[tasks."edit:core"]
#dir = "{{cwd}}/services/core"
#run = "mise r blender:core:{{arg(var=true, default='tasks')}}"