[tools]
# -----------------------------------------------------------------------------
#"aqua:godotengine/godot" = "4.5"

# -----------------------------------------------------------------------------
[tasks."setup"]
description = "Setup project workspace"
#run = "mise i"

[tasks."build"]
description = "Build project artifacts"
#run = [
#  "mise exec -- godot --editor --export-debug Web {{cwd}}/services/game/build/engine/next/index.html"
#]

#[tasks."publish"]
#description = "Publish project artifacts"
#run = [
#  "cp -r {{cwd}}/services/game/build/engine/next {{cwd}}/services/website/public/blob/game/next/index.html"
#]


# -----------------------------------------------------------------------------
[tasks.'github:workflow']
description = "Access to GitHub Actions workflow of the package"
dir = "{{cwd}}"
run = [
  'act -W .github/workflows/mission-hexalife-game-story.yml {{arg(var=true, default="")}}'
]

[tasks.'github:workflow:validate']
description = "Validate GitHub Actions workflow of the package"
depends = [
  'github:workflow --dryrun'
]