[tools]
# -----------------------------------------------------------------------------
"github:inkle/ink" = "1.1.1"

# -----------------------------------------------------------------------------
[tasks."setup"]
description = "Setup project workspace"
#run = "mise i"

[tasks."build"]
description = "Build project artifacts"
run = [
  "mkdir -p {{cwd}}/services/game/build/story/next",
  "mise exec -- inklecate -o {{cwd}}/services/game/build/story/next/story.json {{cwd}}/services/game/story/mission-hexalife-v3.ink"
]
run_windows = [
  'IF NOT EXIST {{cwd}}\services\game\build\story\next (mkdir {{cwd}}\services\game\build\story\next)',
  'mise -v exec -- inklecate -o {{cwd}}\services\game\build\story\next\story.json {{cwd}}\services\game\story\mission-hexalife-v3.ink'
]
depends_post = [
  "publish"
]

[tasks."publish"]
description = "Publish project artifacts"
run = [
  "rm -rf {{cwd}}/services/website/public/blob/story/next || exit 0",
  "cp -r {{cwd}}/services/game/build/story/next {{cwd}}/services/website/public/blob/story/next"
]
run_windows = [
  'IF EXIST {{cwd}}\services\website\public\blob\story\next (RD /S /Q {{cwd}}\services\website\public\blob\story\next)',
  'XCOPY {{cwd}}\services\game\build\story\next {{cwd}}\services\website\public\blob\story\next /E /I'
]

# -----------------------------------------------------------------------------
[tasks.'github:workflow']
description = "Access to GitHub Actions workflow"
run = [
  'gh workflow'
]

[tasks.'github:workflow:run:local']
description = "Execute to GitHub Actions workflow of the package (LOCAL CONTAINER)"
dir = "{{cwd}}"
run = [
  'act -W .github/workflows/mission_hexalife-game-story.yml'
]

[tasks.'github:workflow:run:remote']
description = "Execute to GitHub Actions workflow of the package (REMOTE)"
dir = "{{cwd}}"
run = [
  "gh workflow run mission_hexalife-game-story.yml"
]
