[tools]
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
[tasks."setup"]
description = "Setup packages workspace"
run = [
  "mise //services/game/...:setup",
]

[tasks."build"]
description = "Build packages artifacts"
run = [
  "mise //services/game/...:build"
]

[tasks."publish"]
description = "Deploy packages artifacts"
run = [
  "mise //services/game/...:publish"
]

# -----------------------------------------------------------------------------
[tasks.'github:workflow']
description = "Access to GitHub Actions workflow"
run = [
  'gh workflow'
]

[tasks.'github:workflow:run:local']
description = "Execute to GitHub Actions workflow of the package (LOCAL CONTAINER)"
dir = "{{cwd}}"
run = [
  'act -W .github/workflows/mission_hexalife-game.yml'
]

[tasks.'github:workflow:run:remote']
description = "Execute to GitHub Actions workflow of the package (REMOTE)"
dir = "{{cwd}}"
run = [
  "gh workflow run mission_hexalife-game.yml"
]
