[tools]
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
[tasks."setup"]
description = "Setup project workspace"
run = [
  "mise //services/game/...:setup",
]

[tasks."build"]
description = "Build project artifacts"
run = [
  "mise //services/game/...:build"
]

[tasks."publish"]
description = "Deploy project artifacts"
run = [
  "mise //services/game/...:publish"
]

# -----------------------------------------------------------------------------
[tasks.'github:workflow']
description = "Access to GitHub Actions workflow of the package"
dir = "{{cwd}}"
run = [
  'act -W .github/workflows/mission-hexalife-game.yml {{arg(var=true, default="")}}'
]

[tasks.'github:workflow:validate']
description = "Validate GitHub Actions workflow of the package"
depends = [
  'github:workflow --dryrun'
]
