[tools]
act = "latest"
#gh = "latest"

# -----------------------------------------------------------------------------
[tasks.'website:tasks']
depends = [
    'mise:tasks website {{cwd}}'
]
hide = true
quiet = true

# -----------------------------------------------------------------------------
[tasks."website:core"]
description = "Access to core package"
dir = "{{cwd}}/packages/core"
run = "mise r website:core:{{arg(var=true, default='tasks')}}"

