[tools]
# -----------------------------------------------------------------------------
act = "latest"
#gh = "latest"
# -----------------------------------------------------------------------------
npm = "11.6.0"
node = "22"

# -----------------------------------------------------------------------------
[tasks."setup"]
description = "Setup project workspace"
run = "npm i"

[tasks."build"]
description = "Build project artifacts"
run = "npm run build"


# -----------------------------------------------------------------------------
[tasks."server:start"]
description = "Start server"
run = "npm run dev"

# -----------------------------------------------------------------------------
[tasks.'github:workflow']
description = "Access to GitHub Actions workflow of the package"
dir = "{{cwd}}"
run = [
  'act -W .github/workflows/mission-hexalife-website.yml {{arg(var=true, default="")}}'
]

[tasks.'github:workflow:validate']
description = "Validate GitHub Actions workflow of the package"
depends = [
  'github:workflow --dryrun'
]


