experimental_monorepo_root = true

[settings]
auto_install = true
#trace = true

# -----------------------------------------------------------------------------
#[tasks."mise:tasks"]
#run = [
#    'echo ----------------------------------------',
#    'echo $ mise r {{arg(i=0)}} task',
#    'echo $ mise r {{arg(i=0)}} task:sub-task',
#    'echo ----------------------------------------',
#    'mise -C {{arg(i=1)}} t --no-header'
#]
#hide = true
#quiet = true
